name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # 👇 YEH SABSE IMPORTANT ADDITION HAI 👇
    permissions:
      contents: write 
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          branch: output
          force: true
          message: 'Generate Snake'
